version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: atlas-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: atlas
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 