version: '3.8'
services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    container_name: atlas-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: atlas
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Add initialization scripts for database setup
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - atlas-network

  # ATLAS application
  atlas:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: atlas-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/atlas?schema=public
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret-key-change-in-production}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-placeholder-for-docker-build-only}
      - NEXT_DISABLE_ESLINT=1
    volumes:
      # Mount for local development (uncomment for development)
      - ./:/app
      # Exclude node_modules from the volume mapping
      - /app/node_modules
      - /app/.next
    networks:
      - atlas-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

# Define a custom network for isolation
networks:
  atlas-network:
    driver: bridge

# Define a named volume for data persistence
volumes:
  postgres-data: 